# Fiat Tipo 9-inch custom Android Emulator skin
hw.device.name=Fiat Tipo 9
hw.device.manufacturer=Custom
hw.lcd.width=1280
hw.lcd.height=720
hw.lcd.density=160
hw.touchScreen=yes
hw.mainKeys=no
hw.keyboard=yes
hw.dPad=no
hw.trackBall=no
hw.gps=yes
hw.accelerometer=yes
hw.audioInput=yes
hw.sensors.proximity=no
hw.sensors.orientation=yes
